### ISSUE TITLE
About Avro Type Info error

### ISSUE THREAD

**Issue by mloayzagahona** [okkam-it/flink-examples#4]
Hey.

thanks for the example. I'm trying to run the KafkaFlinkAvroParquet class, but I'm getting this exception.

```
Exception in thread "main" java.lang.RuntimeException: Could not load the AvroTypeInfo class. You may be missing the 'flink-avro' dependency.
	at org.apache.flink.api.java.typeutils.AvroUtils$DefaultAvroUtils.createAvroTypeInfo(AvroUtils.java:120)
	at org.apache.flink.api.java.typeutils.TypeExtractor.privateGetForClass(TypeExtractor.java:1737)
	at org.apache.flink.api.java.typeutils.TypeExtractor.privateGetForClass(TypeExtractor.java:1643)
	at org.apache.flink.api.java.typeutils.TypeExtractor.getForClass(TypeExtractor.java:1639)
	at it.okkam.flink.KafkaFlinkAvroParquet.main(KafkaFlinkAvroParquet.java:52)
```

I've tried manu time in Google, but nothing that fit with this message.

How are you running this example?

Thanks

**Comment by fpompermaier** [comment]
Probably we forget to add the following dependency in the pom.xml:

<dependency>
  <groupId>org.apache.flink</groupId>
  <artifactId>flink-avro</artifactId>
  <version>${flink.version}</version></dependency>

**Comment by fpompermaier** [comment]
With the latest commit (ed6fd12070a32d80f18c8107ef77b9261f3f85f1) this problem should be fixed
